# This file was generated by GoReleaser. DO NOT EDIT.
cask "eunox" do
  version "0.1.0-beta.2"

  on_macos do
    on_arm do
      sha256 "fbae2cdc2804120379f51e00a85b5640c18054665e86be771b0e0072d61e19d4"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ac85979dda02761e2a5001c5b276b2f4ae69e059b976338136659d4c09a6ed2"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b4e7d41f0484600050e5b3e8cfa586e68136d4a32447865946f16cc77e67b74"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eunox"
  desc "Policy-enforcement proxy for MCP servers — deny-by-default capability firewall."
  homepage "https://github.com/eunolabs/eunox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eunox"

  # No zap stanza required

end
