# This file was generated by GoReleaser. DO NOT EDIT.
cask "eunox-mcp" do
  version "0.0.1-rc1"

  on_macos do
    on_arm do
      sha256 "8050422030cc8c4359781e35082edfc30973103c2d8110a49188eecc83d7c9fe"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dcf0ea36006ac35fb083b3187702a24e7271569ad7f71be9b57ae84d8f8ec421"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1910b9baa3fb33e8c3fe0758d08bf8a67520c587081d30ea675a88232f6ac2e"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eunox-mcp"
  desc "Policy-enforcement proxy for MCP servers — deny-by-default capability firewall."
  homepage "https://github.com/eunolabs/eunox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eunox-mcp"

  # No zap stanza required

end
