# This file was generated by GoReleaser. DO NOT EDIT.
cask "eunox-mcp" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "3f0d04d691d90cdeb5231b119c1afb5eb552edeb1b9a6873f86718e4dc418015"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ceadeec556ada7cc645746bb7fcbdb8dcc8c2a21d29a9db9fb4381d62df7acb"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1254739ec1085d70865bfd3a6ba8a781af33246907a174b1c7902dc777e46a91"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e587b4262874b609b8814bfda995530b56f8425ea9fcf015022e9671dd113c5"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eunox-mcp"
  desc "Policy-enforcement proxy for MCP servers — deny-by-default capability firewall."
  homepage "https://github.com/eunolabs/eunox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eunox-mcp"

  # No zap stanza required

end
