# This file was generated by GoReleaser. DO NOT EDIT.
cask "eunox-mcp" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "70b1ec858886673b1ef33e0c0f14525ad0e202e9ddbc13ca75a71a2ee0c83d2f"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9da3ac3d41a7ce96131c76ecd5915613130947b32aa65fc2b75fb382e1e810a"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "776b97b1b364071843fbf4180795fa4ccccbc1e9d9a46842ff882a7256bf2341"
      url "https://github.com/eunolabs/eunox/releases/download/v#{version}/eunox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eunox-mcp"
  desc "Policy-enforcement proxy for MCP servers — deny-by-default capability firewall."
  homepage "https://github.com/eunolabs/eunox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eunox-mcp"

  # No zap stanza required

end
